# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://huynhanhkhoa2707:Khoa123@react.gzfixip.mongodb.net/?appName=React
spring.data.mongodb.database=react

# Server Configuration
server.port=8080

# Google OAuth Configuration
google.oauth.client-id=567861621299-ourpthlk21mr5afff2mtdqc3mh85rkt5.apps.googleusercontent.com
google.oauth.redirect-uri=http://localhost:5173
google.oauth.scope=openid email profile

# Facebook OAuth Configuration
facebook.oauth.app-id=YOUR_FACEBOOK_APP_ID_HERE
facebook.oauth.app-secret=YOUR_FACEBOOK_APP_SECRET_HERE
facebook.oauth.redirect-uri=http://localhost:3000
facebook.oauth.scope=email public_profile

# Spring Boot Configuration
spring.application.name=movie-booking-api

# OpenRouter API Configuration 
openrouter.api.key=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

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khoahagcs230121@fpt.edu.vn
spring.mail.password=ycnn thig iwlc fsny
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL for password reset links
frontend.url=http://localhost:5173